### PR TITLE
Country List Pick takes AppBar Colour value from user

### PR DESCRIPTION
**Pull request by u-gin**

### CODE REVIEW

**Comment by hifiaz** [comment]
can you explain detail for this?

**Comment by u-gin** [comment]
Hello hifiaz, when I used the library I realised the AppBar background colour  automatically picks the theme appear colour.
This particular request makes the user dynamically change the background colour of the AppBar in the SelectionList widget.

**Comment by u-gin** [comment]
Alright, I wish to develop this more, just give me sometime. Thank you.

**Comment by hifiaz** [comment]
thank you very much @u-gin

**Comment by u-gin** [comment]
Hello @hifiaz

**Pull request merged**
